language: python
python: 3.2
before_install:
  - nvm install v8.3
install:
  - npm install -g yarn
  - pip install pyspf
  - pip install py3dns
  - yarn
script:
  npm run test-coverage
after_success:
  npm run coverage
